version: '3'
services:
  node1:
    build: .
    environment:
      - NODE_ID=0
    ports:
      - "50051:50051"
    command: ["python", "run.py", "--node_id=0"]

  node2:
    build: .
    environment:
      - NODE_ID=1
    ports:
      - "50052:50052"
    command: ["python", "run.py", "--node_id=1"]

  # Add more node services as needed

  client:
    build: .
    depends_on:
      - node1
      - node2
    command: ["python", "run.py", "--client"]